CREATE SEQUENCE IF NOT EXISTS item_id_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE authorities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255),
    username  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

CREATE TABLE items
(
    id          BIGINT NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE users
(
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    enabled  BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (username)
);

ALTER TABLE authorities
    ADD CONSTRAINT FK_AUTHORITIES_ON_USERNAME FOREIGN KEY (username) REFERENCES users (username);